Repository Runnect/Runnect-Server, pull requests merged in 2023-01, with the labels that each got.

#11 [Feat] convert time
  src/constant/responseMessage.ts
  src/controller/index.ts
  src/controller/publicCourseController.ts
  src/index.ts
  src/interface/DTO/PublicCourseCreateDTO.ts
  src/module/convert/convertTime.ts
  src/module/convertDataForm.ts
  src/prisma/schema.prisma
  src/router/index.ts
  src/router/publicCourseRouter.ts
  src/service/index.ts
  src/service/publicCourseService.ts
Labels: YuSuhwa-ve

#13 [ Feat ] createPublicCourse
  src/controller/publicCourseController.ts
  src/module/convert/convertTime.ts
  src/router/publicCourseRouter.ts
  src/service/publicCourseService.ts
Labels: YuSuhwa-ve

#24 [Feat] createRecord
  src/constant/responseMessage.ts
  src/controller/index.ts
  src/controller/recordController.ts
  src/interface/DTO/recordDTO.ts
  src/module/convert/convertTime.ts
  src/router/index.ts
  src/router/recordRouter.ts
  src/service/index.ts
  src/service/recordService.ts
Labels: Surin🧡

#26 [Feat] getPublicCourseDetail
  src/constant/responseMessage.ts
  src/controller/publicCourseController.ts
  src/interface/DTO/PublicCourseGetDTO.ts
  src/module/check/checkScrap.ts
  src/router/publicCourseRouter.ts
  src/service/publicCourseService.ts
Labels: YuSuhwa-ve

#34 [Feat] getRecordByUser
  src/constant/responseMessage.ts
  src/controller/recordController.ts
  src/interface/DTO/recordDTO.ts
  src/router/recordRouter.ts
  src/service/recordService.ts
Labels: Surin🧡

#36 [Fix] getPrivateCourseByUser DTO 변경
  src/interface/DTO/PrivateCourseGetDTO.ts
  src/service/courseService.ts
Labels: seonheui

#41 [Feat] signUp
  src/controller/index.ts
  src/controller/userController.ts
  src/router/index.ts
  src/router/userRouter.ts
  src/service/index.ts
  src/service/userService.ts
Labels: seonheui

#43 [Feat] getUser
  src/constant/responseMessage.ts
  src/controller/userController.ts
  src/interface/DTO/UserGetDTO.ts
  src/router/userRouter.ts
  src/service/userService.ts
Labels: seonheui

#46 [Feat] updateUserNickname
  src/constant/responseMessage.ts
  src/controller/userController.ts
  src/interface/DTO/UpdatedUserGetDTO.ts
  src/router/userRouter.ts
  src/service/userService.ts
Labels: seonheui

#44 [Feat] createAndDeleteScrap
  src/constant/responseMessage.ts
  src/controller/index.ts
  src/controller/scrapController.ts
  src/interface/DTO/scrapDTO.ts
  src/router/index.ts
  src/router/scrapRouter.ts
  src/service/index.ts
  src/service/scrapService.ts
Labels: Surin🧡

#48 Feat/#47 getScrapCourseByUser
  src/constant/responseMessage.ts
  src/controller/scrapController.ts
  src/interface/DTO/scrapDTO.ts
  src/router/scrapRouter.ts
  src/service/scrapService.ts
Labels: Surin🧡

#49 [Feat] getCourseDetail
  src/constant/responseMessage.ts
  src/controller/courseController.ts
  src/interface/DTO/CourseDetailGetDTO.ts
  src/router/courseRouter.ts
  src/service/courseService.ts
Labels: seonheui

#53 Fix/#51 parseJsonMiddlewareCreate
  src/controller/courseController.ts
  src/middleware/auth.ts
  src/middleware/index.ts
  src/middleware/multiformDataConvert.ts
  src/module/jwtHandler.ts
  src/router/courseRouter.ts
Labels: YuSuhwa-ve

#55 [Feat] createCourse
  .gitignore
  src/constant/responseMessage.ts
  src/controller/courseController.ts
  src/interface/course/CourseCreateDTO.ts
  src/middleware/multiformDataConvert.ts
  src/module/convert/coorConverPath.ts
  src/module/convert/requestConvertDeparture.ts
  src/prisma/schema.prisma
  src/router/courseRouter.ts
  src/service/courseService.ts
Labels: seonheui

#67 🐛 fix: distance type 변경 (#66)
  src/service/courseService.ts
Labels: seonheui

#69 [Test] recordTestCode
  src/index.ts
  test/record.spec.js
Labels: Surin🧡

#77 [Fix] delete scrap관련 에러처리 로직 추가 (#76)
  src/constant/responseMessage.ts
  src/controller/scrapController.ts
Labels: Surin🧡

#75 [Test] user Test code
  src/controller/scrapController.ts
  src/service/courseService.ts
  src/service/publicCourseService.ts
  src/service/stampService.ts
  test/user.spec.js
Labels: seonheui

#78 [Test] course Test code
  src/controller/publicCourseController.ts
  test/course.spec.js
  test/publicCourse.spec.js
  test/test_img/test_image.jpg
  test/user.spec.js
Labels: seonheui

#88 [Docs] 리드미
  README.md
Labels: seonheui
