Repository Runnect/Runnect-Server, pull requests merged in 2023-04, with the labels that each got.

#123 [Fix] user, PublicCourse 삭제에 따른 제약 조건 변경
  prisma/schema.prisma
Labels: seonheui

#136 [Feat] updatePublicCourse
  src/constant/responseMessage.ts
  src/controller/publicCourseController.ts
  src/interface/DTO/publicCourse/UpdatePublicCourseDTO.ts
  src/router/publicCourseRouter.ts
  src/service/publicCourseService.ts
Labels: Surin🧡

#137 [Feat] updateRecord
  e -i -p ad3ab28
  src/constant/responseMessage.ts
  src/controller/recordController.ts
  src/router/recordRouter.ts
  src/service/recordService.ts
Labels: Surin🧡

#133 [Feat] deletePublicCourse
  src/constant/responseMessage.ts
  src/controller/publicCourseController.ts
  src/router/publicCourseRouter.ts
  src/service/publicCourseService.ts
Labels: seonheui

#135 [Feat] deleteRecord
  src/constant/responseMessage.ts
  src/controller/recordController.ts
  src/router/recordRouter.ts
  src/service/recordService.ts
Labels: seonheui

#140 [Fix] 소셜 로그인 response 변경 (구글)
  src/controller/authController.ts
  src/module/social.ts
Labels: seonheui

#141 [Feat] deleteUser
  src/controller/userController.ts
  src/router/userRouter.ts
  src/service/userService.ts
Labels: seonheui

#143 [Fix]delete public course,delete record 에러로직 추가
  e -i -p ad3ab28
  prisma/schema.prisma
  src/constant/responseMessage.ts
  src/controller/publicCourseController.ts
  src/controller/recordController.ts
  src/router/publicCourseRouter.ts
  src/router/recordRouter.ts
  src/service/publicCourseService.ts
  src/service/recordService.ts
Labels: YuSuhwa-ve

#157 [Feat] changeStampRule
  src/service/stampService.ts
Labels: seonheui

#155 [Feat] addUpdateCourse
  src/service/publicCourseService.ts
Labels: seonheui

#159 [FIX] 본인 public course 스크랩 기능 추가
  src/constant/responseMessage.ts
  src/service/scrapService.ts
Labels: Surin🧡

#162 [Feat] delete apple user
  src/config/index.ts
  src/constant/responseMessage.ts
  src/controller/userController.ts
  src/module/jwtHandler.ts
  src/router/userRouter.ts
  src/service/userService.ts
Labels: YuSuhwa-ve

#165 [Fix] get public cours detail
  src/controller/publicCourseController.ts
  src/service/publicCourseService.ts
Labels: YuSuhwa-ve
